

[[constraint]]
  name = "github.com/cosmos/cosmos-sdk"
  version = "0.29.1"

[[constraint]]
  branch = "master"
  name = "github.com/cosmos/go-bip39"

[[constraint]]
  branch = "master"
  name = "github.com/gopherjs/gopherjs"

[[constraint]]
  name = "github.com/tendermint/tendermint"
  version = "0.27.4"

[[override]]
  name = "golang.org/x/crypto"
  source = "https://github.com/tendermint/crypto"
  revision = "3764759f34a542a3aef74d6b02e35be7ab893bba"


[prune]
  go-tests = true
  unused-packages = true
